"""Some changes

Revision ID: c1902ae50b9d
Revises: 67b390707d34
Create Date: 2024-03-24 21:22:18.831354

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c1902ae50b9d"
down_revision: Union[str, None] = "67b390707d34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "deposits", "current_balance", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "deposits",
        "history",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        nullable=True,
    )
    op.alter_column("targets", "start_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("targets", "start_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column(
        "deposits",
        "history",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        nullable=False,
    )
    op.alter_column(
        "deposits", "current_balance", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
